### ISSUE TITLE
MicrometerMetricsAutoConfiguration requires "application.properties" file 

### ISSUE THREAD

**Issue by kaojo** [dm-drogeriemarkt/micrometer-metrics-wrapper#1]
Hi,

the class MicrometerMetricsAutoConfiguration.java requires the user of this lib to have a "application.properties" file on the classpath. Since many spring-boot app only use application.yml as the main configuration file I suggest to remove the line "@PropertySource(value = "classpath:application.properties")" and let the user decide how to include properties.

Best regards !

**Comment by djohs** [comment]
Good point. This is a leftover of an earlier version, we should remove it. But i think the lib should work nonetheless. We also use this library with application.yml files and it works as well.
